# Generated by Django 3.0.5 on 2021-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetter',
            name='isVarified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
