# Generated by Django 3.0.5 on 2021-04-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questionNumeric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('marks', models.IntegerField()),
                ('correctAns', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='questionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=200)),
                ('noNumeric', models.IntegerField(default=0)),
                ('noTureFalse', models.IntegerField(default=0)),
                ('startingTime', models.DateTimeField()),
                ('durationInMinits', models.IntegerField()),
                ('totalMarks', models.IntegerField(default=0)),
                ('questionNumeric', models.ManyToManyField(to='app.questionNumeric')),
            ],
        ),
        migrations.CreateModel(
            name='questionTureFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('marks', models.IntegerField()),
                ('correctAns', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentAnsNumeric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenAns', models.IntegerField(blank=True, null=True)),
                ('obtainedMarks', models.IntegerField(blank=True, null=True)),
                ('question', models.ManyToManyField(to='app.questionNumeric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('NID', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentAnsTureFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenAns', models.BooleanField(blank=True, null=True)),
                ('obtainedMarks', models.IntegerField(blank=True, null=True)),
                ('question', models.ManyToManyField(to='app.questionTureFalse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='studentAnsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalObtainedMarks', models.IntegerField()),
                ('submissionTime', models.DateTimeField()),
                ('questionSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionSet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
                ('studentAnsNumeric', models.ManyToManyField(to='app.studentAnsNumeric')),
                ('studentAnsTureFalse', models.ManyToManyField(to='app.studentAnsTureFalse')),
            ],
        ),
        migrations.AddField(
            model_name='questionset',
            name='questionSetter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='questionTureFalse',
            field=models.ManyToManyField(to='app.questionTureFalse'),
        ),
        migrations.CreateModel(
            name='examParticipent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionSet')),
                ('student', models.ManyToManyField(to='app.Student')),
            ],
        ),
    ]
